const ResumeApi = [
  {
    id: 1,
    category: "achievment",
    year: "2022",
    title: "Codechef 3 star",
    desc: "Codechef is a online competitive programming platform . I've started my codechef journey from april 2022. Codechef account @ anik0810",
  },
  {
    id: 2,
    category: "achievment",
    year: "2022",
    title: "CSS Certification",
    desc: "Now,I'm a cerified front end developer.",
  },
  {
    id: 3,
    category: "achievment",
    year: "2022",
    title: "HackerRank 5 Star",
    desc: "I've golden badge (5 star) at HackerRank in C.",
  },
  {
    id: 4,
    category: "achievment",
    year: "2022",
    title: "Java Script Certification",
    desc: "Now,I'm a cerified backend end developer.",
  },
  {
    id: 5,
    category: "achievment",
    year: "2022",
    title: "Problem solving Skill Certification",
    desc: "",
    rate: "4.70/5 ",
  },
  {
    id: 6,
    category: "skill",
    year: "2021",
    title: "C",
    desc: "Generate Lorem Ipsum which looks. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante.",
    rate: "4.95/5 ",
  },
  {
    id: 7,
    category: "skill",
    year: "2022",
    title: "C++",
    desc: "Generate Lorem Ipsum which looks. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante.",
    rate: "4.95/5 ",
  },
  {
    id: 8,
    category: "skill",
    year: "2022",
    title: "Java Script",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante.",
    rate: "5.00/5 ",
  },
  {
    id: 9,
    category: "skill",
    year: "2022",
    title: "React Js",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante.",
    rate: "5.00/5 ",
  },
  {
    id: 10,
    category: "skill",
    year: "2022",
    title: "MERN Stack",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante.",
    rate: "5.00/5 ",
  },
]

export default ResumeApi
